events {}

http{
  upstream api_servers {
    server api1:3000;
    server api2:3000;
  }
  server{
    listen 80;
    location / {
      proxy_pass http://api_servers;
    }
  }
  server{
    listen 8080;
    location /stub_status {
        stub_status;
    }
  }
}
